# Generated by Django 4.1.1 on 2022-09-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeCrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
